"""empty message

Revision ID: 11e74f3036db
Revises: d86c5e24e124
Create Date: 2017-02-27 20:17:38.149272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11e74f3036db'
down_revision = 'd86c5e24e124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attackers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'employees', sa.Column('attacker_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'attackers', ['attacker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column(u'employees', 'attacker_id')
    op.drop_table('attackers')
    # ### end Alembic commands ###
