"""empty message

Revision ID: 1b28dd944c6a
Revises: d96d8d8d5c0b
Create Date: 2017-03-19 01:11:49.113945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b28dd944c6a'
down_revision = 'd96d8d8d5c0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('exposition', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'exposition')
    # ### end Alembic commands ###
