"""empty message

Revision ID: 4c44d1ad1d32
Revises: 01863494809b
Create Date: 2017-03-04 20:33:15.429585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c44d1ad1d32'
down_revision = '01863494809b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_attacker', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asset_attacker', 'description')
    # ### end Alembic commands ###
