"""empty message

Revision ID: 54d8026549c4
Revises: 94be03a45ed6
Create Date: 2017-03-02 19:12:41.944971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '54d8026549c4'
down_revision = '94be03a45ed6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'employees_ibfk_4', 'employees', type_='foreignkey')
    op.drop_column('employees', 'asset_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('asset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'employees_ibfk_4', 'employees', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###
