"""empty message

Revision ID: 648238022fae
Revises: b61c0fa884dc
Create Date: 2017-03-04 02:16:34.088816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648238022fae'
down_revision = 'b61c0fa884dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attackers', sa.Column('wert', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attackers', 'wert')
    # ### end Alembic commands ###
