"""empty message

Revision ID: 94be03a45ed6
Revises: 11e74f3036db
Create Date: 2017-03-02 17:49:34.274355

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94be03a45ed6'
down_revision = '11e74f3036db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('analyse_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assets', 'analyses', ['analyse_id'], ['id'])
    op.drop_constraint(u'employees_ibfk_3', 'employees', type_='foreignkey')
    op.drop_column('employees', 'analyse_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('analyse_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'employees_ibfk_3', 'employees', 'analyses', ['analyse_id'], ['id'])
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.drop_column('assets', 'analyse_id')
    # ### end Alembic commands ###
