"""empty message

Revision ID: c24fa57b95f5
Revises: 648238022fae
Create Date: 2017-03-04 02:29:56.032506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c24fa57b95f5'
down_revision = '648238022fae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('wa', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('wu', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'wu')
    op.drop_column('assets', 'wa')
    # ### end Alembic commands ###
