"""empty message

Revision ID: d86c5e24e124
Revises: 135d23697059
Create Date: 2017-02-27 03:41:59.781617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd86c5e24e124'
down_revision = '135d23697059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column(u'employees', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'assets', ['asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column(u'employees', 'asset_id')
    op.drop_table('assets')
    # ### end Alembic commands ###
