"""empty message

Revision ID: d96d8d8d5c0b
Revises: 4c44d1ad1d32
Create Date: 2017-03-17 17:26:36.041930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd96d8d8d5c0b'
down_revision = '4c44d1ad1d32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('criticality', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('sensitivity', sa.Integer(), nullable=True))
    op.drop_column('assets', 'wu')
    op.drop_column('assets', 'wa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('wa', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('wu', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('assets', 'sensitivity')
    op.drop_column('assets', 'criticality')
    # ### end Alembic commands ###
